# Application
spring.application.name=Immobilier Ether
server.port=8080

# PostgreSQL (Render)
spring.datasource.url=jdbc:postgresql://dpg-d7p1dapj2pic73aaqltg-a:5432/immobilier_db_lf69
spring.datasource.username=immobilier_db_lf69_user
spring.datasource.password=9NC2ewfjTEDgtDg0hAbhGphD6PgLXVqV
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#  IMPORTANT (ajoute ça pour éviter bugs)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.mode=HTML

# Logging
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG